logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}[%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate.orm.jdbc.bind: trace
      hibernate.SQL: debug
    com.netflix.graphql.dgs: debug

redis:
  single:
    node: 127.0.0.1:6380
    connect-timeout: 10000
    retry-attempts: 3

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:${SA_MYSQL_DB_PORT}/${SA_MYSQL_DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul
    username: ${SA_MYSQL_DB_USERNAME}
    password: ${SA_MYSQL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    #    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100
  flyway:
    baseline-on-migrate: ${BASELINE_ON_MIGRATE}