logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    org:
      hibernate.orm.jdbc.bind: trace
      hibernate.SQL: debug
    com.netflix.graphql.dgs: debug

redis:
  single:
    node: 127.0.0.1:6380
    connect-timeout: 10000
    retry-attempts: 3

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:${SA_MYSQL_DB_PORT}/${SA_MYSQL_DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul
    username: ${SA_MYSQL_DB_USERNAME}
    password: ${SA_MYSQL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}
    #    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100
  flyway:
    baseline-on-migrate: ${BASELINE_ON_MIGRATE}

cloud:
  aws:
    s3:
      region: ${AWS_S3_REGION}
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}