[versions]
kotlin = "2.0.21"
spring-boot = "3.3.3"
spring-dependency-management = "1.1.3"
mysql-connector-java = "8.0.33"
redisson = "3.36.0"
dotenv = "2.3.1"
testcontainers = "1.20.2"
kotlinlogging = "7.0.0"
kotlinJdsl = "3.5.2"